import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@repo/ui/utils";

import { Providers } from "./_shared/providers/providers";

const inter = Inter({
  subsets: ["latin"],
  fallback: ["sans-serif"],
  display: "swap",
  variable: "--fonts-inter",
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

interface Props {
  params: { locale: string };
}

export default function RootLayout({
  children,
  params,
}: React.PropsWithChildren<Props>) {
  const { locale } = params;

  return (
    <html lang={locale} className={cn("antialiased", inter.variable)}>
      <body>
        <Providers locale={locale}>{children}</Providers>
      </body>
    </html>
  );
}
